### ISSUE TITLE
Reversed axes with item characteristic curves

### ISSUE THREAD

**Issue by wbuchanan** [meyerjp3/jmetrik#2]
Creating example slides for a talk I'm doing tomorrow (17oct2016) on using jMetrik for IRT stuff and the ICC plots have theta on the Y-axis and the probability of endorsing the correct response on the X-axis.  Tried using different configurations, but it will only generate the results in this format.  

![item1](https://cloud.githubusercontent.com/assets/5542790/19417567/53360568-937e-11e6-8695-602c8a588e79.jpg)
![item2](https://cloud.githubusercontent.com/assets/5542790/19417568/533edb34-937e-11e6-96e7-7c676ac272e5.jpg)
![item3](https://cloud.githubusercontent.com/assets/5542790/19417569/53428612-937e-11e6-8ddb-007746b96969.jpg)
![item4](https://cloud.githubusercontent.com/assets/5542790/19417570/534f4a50-937e-11e6-93d6-9d42fda6119a.jpg)
![item5](https://cloud.githubusercontent.com/assets/5542790/19417571/5352165e-937e-11e6-874d-84c6bd904980.jpg)
![item6](https://cloud.githubusercontent.com/assets/5542790/19417572/535d48d0-937e-11e6-8b25-709719360a5c.jpg)
![item7](https://cloud.githubusercontent.com/assets/5542790/19417573/535e39f2-937e-11e6-9d92-5c1d09325a97.jpg)
![item8](https://cloud.githubusercontent.com/assets/5542790/19417574/536a64e8-937e-11e6-87ac-a8c7f0108fec.jpg)
![item9](https://cloud.githubusercontent.com/assets/5542790/19417575/53705240-937e-11e6-87bf-b877f173e0ae.jpg)
![item10](https://cloud.githubusercontent.com/assets/5542790/19417576/5377b8fa-937e-11e6-9b11-aebddf82c7fa.jpg)

**Comment by meyerjp3** [comment]
You have changed the default setting for the plots. To change the settings and have Theta appear on the x-axis, follow these steps:
1. Click Edit > Preferences in the main menu. This will display the preferences dialog.
2. Select the Chart Options tab.
3. In the Display Options panel, be sure that "Vertical Orientation" is selected. (You can also click the "Reset to Default Chart Options" to reset all chart preferences to the default values)
4. Select the Program Options tab and then click the OK button.
