### ISSUE TITLE
Rasch Person Estimation Selection Window Title

### ISSUE THREAD

**Issue by Sifor** [meyerjp3/jmetrik#3]
Under Rasch person tab, Person estimation panel, there is a typo. When selcting the data set to use, after hitting the 'select' button for the Person estimation, the window that comes up is labeled "delete table." It doesn't functionally delete anything, but is rather throwing to a group of users (n=12) today.

**Comment by meyerjp3** [comment]
I don't see the "Delete Table" label there. I did find it in IRT Plot when pressing the "Select" Button on the "Points" tab. The dialog that appears shows "Delete Table" as the title. You are right that the error is in the title only. It won't delete anything. 

I corrected the title and pushed the changes to GitHub. It will be visible in jMetrik on the next release of the binaries.
