### ISSUE TITLE
Item Analysis Typo

### ISSUE THREAD

**Issue by Sifor** [meyerjp3/jmetrik#4]
Reliability is misspelt as 'RELIABILIY' in two places on Item Analysis: Reliability Analysis and Item Group Definied Part-Test Reliability.

Item Analysis on Likert with Pearson correlation.
Options checked (exhaustive):
Compute item statistics
Correct for spuriousness
Show headers

**Comment by meyerjp3** [comment]
Thanks. I have corrected the misspelled words. The errors were in the psychometrics library.
